### ISSUE TITLE
Fail CIF conversion

### ISSUE THREAD

**Issue by danieleongari** [lsmo-epfl/curated-cofs-submission#13]
I struggled ENORMOUSLY to deal with this CIF:
[P-StPtDm-COF.cif.txt](https://github.com/lsmo-epfl/curated-cofs-submission/files/4782327/P-StPtDm-COF.cif.txt)

- ASE and pymatgen fail to correctly unwrap the symmetry
- I had also some problems with `manage_crystal -rotaxis`

The only way was finally to open it with VESTA, export the CIF and use that as input for the submission. 
[P-StPtDm-COF_vesta.cif.txt](https://github.com/lsmo-epfl/curated-cofs-submission/files/4782338/P-StPtDm-COF_vesta.cif.txt)

**Comment by ltalirz** [comment]
> ASE and pymatgen fail to correctly unwrap the symmetry

Wow... are you sure the CIF file is correct?
If yes, we should report this.

**Comment by danieleongari** [comment]
After further investigation, it looks like:

* for ASE it unwraps a bad symmetry without any warning

* for pymatgen it works only if instead of symmetry. symbol "P2" one uses the index
```
_space_group_IT_number                 3
```

It might be that "P2" is an ambiguous symbol that refers to different symmetries depending on the cell and Vesta's parser is the only correct one which can compare symbol and cell to understand it correctly.

**Comment by danieleongari** [comment]
Indeed from this list (https://www.psi.ch/sites/default/files/import/lns-diffraction/Support2EN/Symmetry_Elements_of_all_Space_Groups.pdf) it seems that `P2` is the Hall symbol and not the H-M symbol. 
For `P6`,  which is very common in COFs, it is the same symbol. for both notation, but this is not the case for `P2` which in H-M notation translates to 'P 1 2 1`.

**Comment by ltalirz** [comment]
Torbjörn Björkman (the author of the [cif2cell](https://github.com/torbjornbjorkman/cif2cell) tool) mentioned this just last week at the optimade workshop - Herrmann Mauguin notation is a big mess (e.g. the strings "Pnn:2", "Pnnn2" and "PnnnZ" have all been called H-M symbols by different people and map into the "-P 2ab 2bc" Hall symbol).

If possible, we should only use Hall sybmols.

This code may be useful:
https://github.com/torbjornbjorkman/cif2cell/blob/516436f02f9fed5440da5942a4bfe1dda959bf0e/cif2cell/spacegroupdata.py#L19-L24

**Comment by danieleongari** [comment]
This is the file that ASE is using for the symmetries: https://github.com/rosswhitfield/ase/blob/b7212f7f2d6055e48d395648cb3d2bba9f76f4a3/ase/spacegroup/spacegroup.dat
...and it looks like ASE reads the HM symbol but this is. interpreted as a Hall symbol.
Not clear what settings 1 and 2 are.

**Comment by danieleongari** [comment]
After some testing I saw that pymatgen reads the symbols using the H-M notation (whatever is the label: `hm`, hm_alt` or `hall`) and therefore one should check if the symbol is specified with the proper notation, comparing with this file https://github.com/materialsproject/pymatgen/blob/82e053d67564248e8c34a230e465893735a3cda8/pymatgen/symmetry/symm_ops.yaml

I still could not manage to understand how ASE works. 
We might consider to switch to PMG.

**Comment by ltalirz** [comment]
> Not clear what settings 1 and 2 are.

"Some spacegroups have more than one setting." 
https://wiki.fysik.dtu.dk/ase/_modules/ase/spacegroup/spacegroup.html
I guess the representation in terms of symmetry operations in CIF is not entirely unique, even when you have the space group number.

Interesting: https://github.com/materialsproject/pymatgen/blob/82e053d67564248e8c34a230e465893735a3cda8/pymatgen/symmetry/symm_ops.yaml#L1-L2

**Comment by danieleongari** [comment]
It seems to be a very specific problem
