### ISSUE TITLE
Auto completion not working propertly

### ISSUE THREAD

**Issue by danieleongari** [lsmo-epfl/curated-cofs-submission#14]
The problem with auto completion is that you can only chose among the already present string and modification are not stored.

Therefore,
* if you write your own comment in `CIF modifications` this gets saved as None
* if you pick one in the list and you modify it, modifications are not stored
* if you change manually from e.g., 2D to 3D this is not stored

**Comment by ltalirz** [comment]
thanks for pointing this out - I didn't realize this.
unfortunately, this is not yet supported https://github.com/holoviz/panel/issues/685

I.e. we cannot use autocomplete here.
The only use case where the current implementation of the AutocompleteInput makes sense is when you have a very long but fixed list to choose from (and I'm not sure this is currently the case for any of our fields)

**Comment by danieleongari** [comment]
@ltalirz 
Another problem I just discovered is that `None` gets printed with quotes `"none"`,
which will be misinterpreted when loaded with `pandas.read_csv()`.
https://raw.githubusercontent.com/danieleongari/CURATED-COFs/update_2nd_2020/cof-frameworks.csv

**Comment by danieleongari** [comment]
Fixed by upgrading Bokeh to `2.3.0.dev` https://github.com/lsmo-epfl/curated-cofs-submission/pull/22
