### ISSUE TITLE
perhaps warning if COF name is already used

### ISSUE THREAD

**Issue by ltalirz** [lsmo-epfl/curated-cofs-submission#4]

**Comment by danieleongari** [comment]
In the new COFs release of Feb20 we are avoiding duplicated conventional names, by using "First-Author-Surname's COF-name".
Therefore, we want do definitively introduce this check in the submission form.

**Comment by danieleongari** [comment]
I think it is fine in the workflow, to keep this check for the last stage when one commits the update, and has a broader overview the database as a whole: here the scope is to submit new entries one by one
